### ISSUE TITLE
Question about the license change

### ISSUE THREAD

**Issue by tothandras** [nodeca/argparse#159]
We've noticed that prior version `2.0` the library was distributed under the `MIT` license, compatible with most open- and closed-source projects. We were using your library, but unfortunately, going forward we won't be able to only because of the incompatibility with the `Python-2.0` license. It would be very helpful if you could shed some light on the necessity to change it. Thank you!

**Comment by puzrin** [comment]
Since sources are "very close" (really) to original (intended), we just used original license, without any hidden meaning. Just to avoid any claims about ufair use of upstream.

AFAIK, original license is opensouce and not restrictive. If you have any problems with it or ideas how to improve - let me know. I don't care about propomoting my personal name in copyright an not wish to apply any restrictions. So, i'm ok to replace licence with anything else valid, if upseam authors don't worry about (for example, if you ask upseam guys confimaion about using MIT by this port - i'm ok to use MIT back).

Could you clarify, what's wrong with Python-2.0?

**Comment by tothandras** [comment]
@puzrin There was a misunderstanding on our side. I'm not an expert in licenses and I asked around in the office when the build failed for an unrecognised license type. We had the initial impression that `Python-2.0` is similar to `GPL`, which we are incompatible with, but by taking a second look we realised it's okay to use. Sorry for the noise! 🙂

**Comment by tmtron** [comment]
>Could you clarify, what's wrong with Python-2.0?

Python-2.0 is unexpected and not widely used in JS/node development.  
e.g. I first thought that our license check code had an issue parsing licenses and that it was somehow picking up some pyhton code or libs.  
When looking at some other issues here, it seems I'm not the only one.  

Another issue is that we must now pay again for a lawyer to check if this license is really okay to use (for MIT, Apache2, etc. we have already done that).  
And only when the lawyer says, it's okay, we can update all depending packages and also our license check-code.

So MIT would be much preferred.

**Comment by puzrin** [comment]
> Python-2.0 is unexpected and not widely used in JS/node development.

Argparse MUST use "some of python license", this can not be changed. Please, read my explanations in previous issues prior to suggest "obvious to decline things".

**Comment by tmtron** [comment]
I did read your explanations and I didn't mean to decline anything.
I just answered your question "what's wrong with Python-2.0?", since it seems that you were not aware of these implications.

**Comment by puzrin** [comment]
IMO there are no problem with license compatibility. The only problem is some peopple don't trust this and have to apply some efforts for check. But instead of paying to lawyer, they wish to drill my brain for free :). I can understand that, but can't agree with that :). According to OSS principle, constructive solution is to investigate issue once and share result for all. And IMO such things should not be addressed to me.
