### ISSUE TITLE
npm packages out of sync: argparse and @types/argparse

### ISSUE THREAD

**Issue by melonmouse** [nodeca/argparse#172]
**The symptoms**

Got an unexplained `TypeError: simpleExample.add_argument is not a function` when trying to use argparse in typescript (using an example from the docs). Almost switched to yargs because of it.

**The cause**

The npm package `@types/argparse` defaulted to version `2.0.10` for me, while `argparse` defaulted to `argparse@1.0.10`. These are not compatible and cause errors for any of the functions that [had their names changed from v1 to v2](https://github.com/nodeca/argparse/blob/master/doc/migrate_v1_to_v2.md). 
Installing the newer version of argparse explicitly fixed it for me:
`npm install argparse@2`
This went wrong on npm versions 7.11.2 and 9.2.0.

**Possible fixes**

- upgrade the default of `argparse` to `2.0.10`
- persuade the people at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) to downgrade the default version of `@types/argparse` to 1.0.10
- update dependency requirements so npm either installs compatible versions or complains when installing incompatible versions

I also created a discussion in the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/63645

**p.s.**
Thanks for porting argparse to javascript! To me, it feels like a breath of fresh air compared to yargs which to me seems unsafe/overly complicated for its purpose.

**Comment by rlidwka** [comment]
By default, npm will install latest versions:

```
$ yarn add argparse
$ yarn add @types/argparse
$ yarn list
yarn list v1.22.10
├─ @types/argparse@2.0.10
└─ argparse@2.0.1
Done in 0.23s.
```

It is likely that you have older version of argparse because one of your existing dependencies requires it. And instead of installing duplicate versions, package manager decides to just give you an old one. But that dependency doesn't use typescript, so you will get newest version of types as a default.

To ensure that you install latest version, use `npm install argparse --latest`.

It's definitely not an issue with this package. Maybe ask people at DefinitelyTyped for setting up peer dependency requirement, although I have no idea how that works in practice.

**Comment by melonmouse** [comment]
Thanks for taking a look! I can't verify what happened when I reported this, but your explanation is definitely plausible.

The peer dependency requirement is the direction the other thread is taking: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/63645

Closing this one.

Thanks again!
