### ISSUE TITLE
FileType

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#51]
The Python `FileType` accepts a filename string, and returns an opened file, or returns an `ArgumentTypeError` with the IOError message.  It can also return stdin or stdout if the string is '-'.

I think a nodejs equivalent would be a `ReadStream` or `WriteStream`, or `process.stdin, stdout`, which are also streams.  Opening the file first (with `fs.openSync`), before creating the stream, lets argparse return an error message if there is a problem.

I propose submitting this type as an example file, with a unix `cat` like functionality.  This type is probably not as useful in nodejs as in Python, since node is meant more for asynchronous server like applications than for scripting.

**Comment by piranna** [comment]
Honestly, probably this would be the best feature of `argparse` and the main reason to use it, `FileType` is awesome, and returning a stream in Node.js instead makes totally sense. This could also open the door to use other custom argument checkers...

**Comment by rlidwka** [comment]
Ported from python as part of argparse 2.0 (as `process.stdout` for `-` or `fs.createWriteStream` otherwise).

Keep in mind that you can close fs streams with `stream.close()`, and stdout (which shouldn't be closed) conveniently doesn't have such method.

Maybe it needs some examples, I feel like FileType is one of the less clear parts in all of this.

**Comment by piranna** [comment]
Does this also works to read files?

**Comment by rlidwka** [comment]
yeah, FileType('r') to read and FileType('w') to write, same as python
